env:
  global:
  - CC_TEST_REPORTER_ID=432b7af74cde04aae48f014c1cced555e270c79e8ff6f7dee4615e66f5ba111c

sudo: false
language: java
jdk:
- oraclejdk8
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
-

after_script:
# Upload code coverage to code climate - with workaround for jacoco (Dec 2017)
- cp application/build/reports/jacoco/test/jacocoTestReport.xml application/src/main/kotlin/jacoco.xml
- cd application/src/main/kotlin
- ../../../../cc-test-reporter after-build -t jacoco --exit-code $TRAVIS_TEST_RESULT
